language: android

android:
  components:
    - build-tools-23.0.2
    - android-23
    - add-on
    - extra
  licenses:
    - android-sdk-license-5be876d5

jdk:
  - oraclejdk7

script:
  - ./gradlew clean build check

notifications:
  email: false

sudo: false

cache:
  directories:
    - $HOME/.gradle